const items = [
    {
        id: '001',
        image:'1.png',
        rating:'Jordan',
        company:'WMNS AIR JORDAN 1 MID SE',
        iteam_name:'WHITE/GREY ICE BLUE',
        current_price:12295.00,
        delivery_date: '10 Oct 2024',
        return_period: 14,
    },
    {
        id: '002',
        image:'2.png',
        rating:'Nike',
        company:'AIR FORCE 1.07',
        iteam_name:'WHITE/UNIVERSITY GOLD WHITE',
        current_price:9695.00,
        delivery_date: '10 Oct 2024',
        return_period: 14,
    },
    {
        id: '003',
        image: '3.png',
        rating:'Adidas Originals',
        company: 'SAMBA OG',
        item_name: 'BLACK WHITE/COLLEGIATE GREEN',
        current_price: 10999.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },
    {
        id: '004',
        image: '4.png',
        rating:'Jordan',
        company:'WMNS AIR JORDAN 1 LOW OG',
        item_name: 'BLACK/GORGE GREEN',
        current_price: 12799.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },
    {
        id: '005',
        image: '5.png',
        rating:'Nike',
        company:'AIR FORCE 1.07',
        item_name: 'TRIPLE WHITE',
        current_price: 7795.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        
    },
    {
        id: '006',
        image: '6.png',
        rating:'Nike',
        company:'WMN DUNK LOW NEXT NATURE SE',
        item_name: 'SEA GLASS',
        current_price: 10795.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },
    {
        id: '007',
        image: '7.png',
        rating:'Nike',
        company:'WMN AIR MAX 90 LV8',
        item_name: 'SUNNIT WHITE/SMOKE GREY-BLACK',
        current_price: 7795.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },
    {
        id: '008',
        image: '8.png',
        rating:'New Balance',
        company:'574',
        item_name: 'GREEN/SEA SALT',
        current_price: 9999.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    }
    /*{
        id: '009',
        image: '91.png',
        rating:'Nike',
        company:'AIR MORE UPTEMPO 96',
        item_name: 'WHITE/NAVY-METALLIC',
        current_price: 15995.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },
    {
        id: '010',
        image: '92.png',
        rating:'Jordan',
        company:'SPIZIKE LOW',
        item_name: 'WHITE/PURE PLATINUM',
        current_price: 12749.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },
    {
        id: '011',
        image: '93.png',
        rating:'Jordan',
        company:'AIR JORDAN 6 RETRO',
        item_name: 'WHITE/BLACK',
        current_price: 18395.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },
    {
        id: '012',
        image: '94.png',
        rating:'Jordan',
        company:'WMNS AIR JORDAN 1 LOW OG',
        item_name: 'WHITE/MILK-VIVID SULFUR',
        current_price: 15995.00,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    }*/

];